---
- name: Set System Timezone
  timezone:
    name: "{{ timedatectl_timezone }}"
  when: ansible_service_mgr == "systemd"

- name: Setup timesyncd config
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
  when: ansible_service_mgr == "systemd"

- name: Enable NTP
  command: timedatectl set-ntp true
  notify: Restart timedatectl
  when: ansible_service_mgr == "systemd"
